services:
  backend:
    container_name:  app-backend
    image: app-backend
    command: sh -c "npm install && npm start"
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      PORT: 3000
      FRONTEND_URL: http://localhost:4200
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: data1
  frontend:
    container_name: app-frontend
    image: app-frontend
    command: sh -c "npm install && npm start"
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - backend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      VUE_APP_PORT: 4200
      VUE_APP_BACKEND_URL: http://localhost:3000/api
  mysql:
    image: mysql:8.0
    volumes:
      - test-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: data1
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql

volumes:
  test-mysql-data:
